#! /usr/bin/env bash
set -e

[[ "$TOXENV" == *-flake8 || "$TOXENV" == pypy* ]] && exit 0

umask 022 &&
chmod -R a+rX . &&

pip install -U pip setuptools "wheel==0.31.1" twine &&
python setup.py sdist &&

if [ -d build ]; then find build -name '*.py[co]' -delete; fi &&
python setup.py build_ext &&
python setup.py build --executable '/usr/bin/env python' &&
python    -m compileall build &&
python -O -m compileall build &&
python setup.py bdist_wheel &&

py=$(python -c "import sys; print('.'.join(sys.version.split('.')[:2]))")
v=$(echo "$py" | sed 's/\.//') &&

if [ "$TRAVIS_OS_NAME" == 'linux' ]; then

    pip install -U auditwheel &&

    for f in dist/Cheetah3-*-cp$v-*-linux_x86_64.whl; do
        python -m auditwheel repair -w dist/ "$f" &&
        rm -f "$f"
    done

fi &&

# TWINE_USERNAME / TWINE_PASSWORD / TWINE_REPOSITORY_URL
# must be set in Travis settings.
twine upload --repository-url $TWINE_REPOSITORY_URL --skip-existing dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD
